apiVersion: v1
kind: Pod
metadata:
  name: pod-nautilus
  labels:
     app:nginx
spec:                         
  containers:                 
    - name: container-nautilus
      image: nginx:latest                 
      ports:                              
         - containerPort: 80              
      volumeMounts:                       
        - mountPath: /usr/share/nginx/html
          name: web-storage    
  volumes:                     
    - name: web-storage        
      persistentVolumeClaim:   
        claimName: pvc-nautilus